spring:
  application:
    name: movie-info-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true  
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8091

app:
  id: ${random.uuid}