spring:
  application:
    name: microservice2-MovieCatalogService

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true  
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/

server:
  port: 8096

app:
  id: ${random.uuid}
  
