spring:
  application:
    name: microservice3-RatingDataService

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true  
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8094

app:
  id: ${random.uuid}